# Generated by Django 3.0 on 2022-06-09 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porteiros', '0001_initial'),
        ('visitantes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Visitantes',
            new_name='Visitante',
        ),
    ]
