# Generated by Django 3.0 on 2022-06-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=194, unique=True, verbose_name='E-mail do usuário'),
        ),
    ]
